name: sfft
channels: !!python/tuple
- defaults
- https://conda.anaconda.org/conda-forge
- https://conda.anaconda.org/menpo
dependencies:
- colorama=0.3.7=py35_0
- cycler=0.10.0=py35_0
- icu=57.1=vc14_0
- jpeg=9b=vc14_0
- libpng=1.6.27=vc14_0
- matplotlib=2.0.0=np112py35_0
- menpo::opencv3=3.1.0=py35_0
- mkl=2017.0.1=0
- numpy=1.12.0=py35_0
- openssl=1.0.2k=vc14_0
- pip=9.0.1=py35_1
- py=1.4.32=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_2
- pytest=3.0.6=py35_0
- python=3.5.3=0
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- qt=5.6.2=vc14_3
- setuptools=27.2.0=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- tk=8.5.18=vc14_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
- zlib=1.2.8=vc14_3
- pip:
  - hypothesis==3.6.1

